### ISSUE TITLE
Customization of the First Day of the Week 

### ISSUE THREAD

**Issue by AmirhosseinRHT** [antoniandre/vue-cal#2]
Hi,
I think a important feature that you can add to new version of vue-cal , is the ability to customize first day of the week with a prop.
Is this possible?

**Comment by antoniandre** [comment]
It's already possible, here's a spoiler! ;)
<img width="990" alt="Screenshot 2024-11-24 at 14 31 31" src="https://github.com/user-attachments/assets/db087d11-e611-4b3b-b649-6fe9604457ae">
