### ISSUE TITLE
Set current time

### ISSUE THREAD

**Issue by jmthomas** [antoniandre/vue-cal#6]
My calendar application has to support local time as well as UTC. I'm able to do this by simply adding the timezone offset to all my events and thus make it look like UTC. However, the [current time](https://antoniandre.github.io/vue-cal/#ex--today-current-time) doesn't seem to be able to be set. I tried setting the `selected-date` but that appears to be date only (aptly named).

Is there a way to force the time to the value I want to simulate UTC?

**Comment by antoniandre** [comment]
Hi @jmthomas, in V4 there is no way and it's the last version of v4. 
But in the v5, where you have created this issue, I will think about it and add it to the todo list, I should be doable without too much rework I think.

The first pre-release should be next January

**Comment by jmthomas** [comment]
I mean natively supporting timezones would be even more awesome but I'd settle for this small hack. :-)
