### ISSUE TITLE
Weeknumbers are not correctly aligned when using events-on-month-view

### ISSUE THREAD

**Issue by FJPEXL** [antoniandre/vue-cal#8]
As you can see, when using event-on-month-view weeknumbers become incorrectly aligned.

![image](https://github.com/user-attachments/assets/d910eeb0-e69f-424c-bc44-cd338a364098)
![image](https://github.com/user-attachments/assets/e330d9ba-7ad3-46a6-aaab-af0993b98318)

**Comment by antoniandre** [comment]
hi @FJPEXL Vue Cal v4 has the minimum vital styles. 
It's easy to set a cell height with overflow auto if that's what you want. then the week numbers will be aligned.

**Comment by antoniandre** [comment]
btw, This repo is only for V5. V4 is here: https://github.com/antoniandre/vue-cal-v4
